version: "3.9"

services:
  web:
    build: .
    command: daphne vu.asgi:application --bind 0.0.0.0 --port 8000
    volumes:
      - ./:/vu/
      - static_volume:/vu/static
      - media_volume:/vu/media
    ports:
      - 8000:8000
    env_file:
      - ./env

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - 80:80
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - static_volume:/vu/static
      - media_volume:/vu/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
